### ISSUE TITLE
Could not find a valid gem 'logstash-input-zendesk.gemspec' (>= 0) in any repository

### ISSUE THREAD

**Issue by prashanttct07** [ppf2/logstash-input-zendesk#2]
Hi Team,

I donwloaded the ,master version from git and while running the gem install I am getting the below error , can anyone let me know how I can solve the same.

sudo gem install logstash-input-zendesk.gemspec
ERROR:  Could not find a valid gem 'logstash-input-zendesk.gemspec' (>= 0) in any repository

**Comment by ppf2** [comment]
This plugin has not yet been added to the Logstash plugin ecosystem.  So you will have to build and install it locally like the following:

After downloading the master files, you have to build the gem file first `gem build logstash-input-zendesk.gemspec` (i.e. https://www.elastic.co/guide/en/logstash/current/_how_to_write_a_logstash_input_plugin.html#_build) which will give you a gem `logstash-input-zendesk-2.0.0.gem`.  Then you can install it as a local gem to your Logstash instance (eg. Step 2 of https://www.elastic.co/guide/en/logstash/current/_how_to_write_a_logstash_input_plugin.html#_test_installation).
